export enum ExerciseName {
  BENCH_PRESS = 'Bench Press',
  INCLINE_BENCH_PRESS = 'Incline Bench Press',
  OVERHEAD_PRESS = 'Overhead Press',
  LATERAL_RAISE = 'Lateral Raise',
  TRICEP_PUSHDOWN = 'Tricep Pushdown',
  SQUAT = 'Squat',
  LEG_PRESS = 'Leg Press',
  LEG_CURL = 'Leg Curl',
  LEG_EXTENSION = 'Leg Extension',
  CALF_RAISE = 'Calf Raise',
  DEADLIFT = 'Deadlift',
  PULL_UP = 'Pull Up',
  LAT_PULLDOWN = 'Lat Pulldown',
  BARBELL_ROW = 'Barbell Row',
  SEATED_ROW = 'Seated Row',
  BICEP_CURL = 'Bicep Curl',
  HAMMER_CURL = 'Hammer Curl',
}
